package sistMovie.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import sistMovie.vo.MemberVO;

/**
 * Model class of 설문참여.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class VoteVO implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 선택항목. */
	private int oneTwo;

	/** 설문참여일. */
	private String voteDate;

	/** 회원정보. */
	private List<MemberVO> memberList;

	/*회원 ID*/
	private String id;
	/** 설문조사. */
	private List<SurveyVO> surveyList;


	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public int getOneTwo() {
		return oneTwo;
	}

	public void setOneTwo(int oneTwo) {
		this.oneTwo = oneTwo;
	}

	public String getVoteDate() {
		return voteDate;
	}

	public void setVoteDate(String voteDate) {
		this.voteDate = voteDate;
	}

	public List<MemberVO> getMemberList() {
		return memberList;
	}

	public void setMemberList(List<MemberVO> memberList) {
		this.memberList = memberList;
	}

	public List<SurveyVO> getSurveyList() {
		return surveyList;
	}

	public void setSurveyList(List<SurveyVO> surveyList) {
		this.surveyList = surveyList;
	}
}