package exam.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 설문참여 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class VoteVO implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

//	/** 설문조사. */
//	private SurveyVO tSurvey;
//
//	/** 회원정보. */
//	private MemberVO tMember;
	
	private int survey_no;
	
	private String id;
	/** 선택항목. */
	private String oneTwo;

	/** 설문참여일. */
	private Date voteDate;

	
	
	
	public VoteVO(int survey_no, String id, String oneTwo) {
		this.survey_no = survey_no;
		this.id = id;
		this.oneTwo = oneTwo;
	}

	public int getSurvey_no() {
		return survey_no;
	}

	public void setSurvey_no(int survey_no) {
		this.survey_no = survey_no;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOneTwo() {
		return oneTwo;
	}

	public void setOneTwo(String oneTwo) {
		this.oneTwo = oneTwo;
	}

	public Date getVoteDate() {
		return voteDate;
	}

	public void setVoteDate(Date voteDate) {
		this.voteDate = voteDate;
	}

	


}
