package exam.madang;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 도서 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class NewBookMd implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 도서번호. */
	private Integer bookid;

	/** 도서이름. */
	private String bookname;

	/** 도서단가. */
	private Integer price;

	/** 출판사. */
	private NewPublisherMd newPublisher;

	/** 주문 목록. */
	private Set<NewOrderMd> newOrderSet;

	/**
	 * 생성자.
	 */
	public NewBookMd() {
		this.newOrderSet = new HashSet<NewOrderMd>();
	}

	/**
	 * 도서번호을 설정합니다..
	 * 
	 * @param bookid
	 *            도서번호
	 */
	public void setBookid(Integer bookid) {
		this.bookid = bookid;
	}

	/**
	 * 도서번호을 가져옵니다..
	 * 
	 * @return 도서번호
	 */
	public Integer getBookid() {
		return this.bookid;
	}

	/**
	 * 도서이름을 설정합니다..
	 * 
	 * @param bookname
	 *            도서이름
	 */
	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	/**
	 * 도서이름을 가져옵니다..
	 * 
	 * @return 도서이름
	 */
	public String getBookname() {
		return this.bookname;
	}

	/**
	 * 도서단가을 설정합니다..
	 * 
	 * @param price
	 *            도서단가
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * 도서단가을 가져옵니다..
	 * 
	 * @return 도서단가
	 */
	public Integer getPrice() {
		return this.price;
	}

	/**
	 * 출판사을 설정합니다..
	 * 
	 * @param newPublisher
	 *            출판사
	 */
	public void setNewPublisher(NewPublisherMd newPublisher) {
		this.newPublisher = newPublisher;
	}

	/**
	 * 출판사을 가져옵니다..
	 * 
	 * @return 출판사
	 */
	public NewPublisherMd getNewPublisher() {
		return this.newPublisher;
	}

	/**
	 * 주문 목록을 설정합니다..
	 * 
	 * @param newOrderSet
	 *            주문 목록
	 */
	public void setNewOrderSet(Set<NewOrderMd> newOrderSet) {
		this.newOrderSet = newOrderSet;
	}

	/**
	 * 주문를 추가합니다..
	 * 
	 * @param newOrder
	 *            주문
	 */
	public void addNewOrder(NewOrderMd newOrder) {
		this.newOrderSet.add(newOrder);
	}

	/**
	 * 주문 목록을 가져옵니다..
	 * 
	 * @return 주문 목록
	 */
	public Set<NewOrderMd> getNewOrderSet() {
		return this.newOrderSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bookid == null) ? 0 : bookid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		NewBookMd other = (NewBookMd) obj;
		if (bookid == null) {
			if (other.bookid != null) {
				return false;
			}
		} else if (!bookid.equals(other.bookid)) {
			return false;
		}
		return true;
	}

}
